### ISSUE TITLE
Running child process has exited and the iris's reloading does not work

### ISSUE THREAD

**Issue by w20089527** [kataras/rizla#1]
When I modified a go file, the iris detected it changed. But the file I modify has some syntax errors, the iris will give some build error. For example:

![image](https://cloud.githubusercontent.com/assets/7413974/16940163/7ede9af4-4dba-11e6-9f0b-9fc8ada30346.png)

After I finished the go file, in other words it has no syntax errors, the iris detected the changes, and then  it will rebuild and reload. But it gave me an error. As follows:

![image](https://cloud.githubusercontent.com/assets/7413974/16940375/10608126-4dbc-11e6-9b20-df0b4e4b492e.png)

And I have looked up the error code, it stands for "No Waiting Child Process".
The problem is caused when killing a non-existent process.
I have checked the rizla code, maybe we can take this exception as a friendly one.

![image](https://cloud.githubusercontent.com/assets/7413974/16940681/03584a34-4dbe-11e6-8407-a01405bc5a7a.png)

**Comment by ghost** [comment]
Reference: https://github.com/kataras/iris/issues/304#issuecomment-233811588

**Comment by kataras** [comment]
@whrool I'm surprised, you was correct! I am adding some things and fix two-times reload on windows and I will push the commit, the issue has been solved, ( I didn't notice it before because I tested with only first error before a succesfuly run, and it was worked) Thanks you very much!

**Comment by ghost** [comment]
I'm surprised, you was correct but we don't want to remove this error, I just fixed it with `if err := proc.Release(); err !=nil { return nil }` on the killing proc, but you got the point!! Thanks you. Some other things fixed also, you can upgrade with `go get -u github.com/kataras/rizla`
