### ISSUE TITLE
Goland IDE Ctrl+S not surport

### ISSUE THREAD

**Issue by aisq2008** [kataras/rizla#12]
Use Goland to save a .go file with Ctrl+S ,not reload the program.

**Comment by kataras** [comment]
This is `Jetbrains` issue, it doesn't saves the file as most code editors and IDEs do; using the Operating System's calls. I think `Jetbrains` added an option that you can disable this behavior and use the standard operating system's method, if you find that setting and play with it, it will work :), post an issue at jetbrains if you can't find the option.

**Comment by aisq2008** [comment]
thank you,i had solved the problem by uncheck the  option [ ] use "safe write" (save changes to a temporary file first) in the goland behavior setting

**Comment by kataras** [comment]
You're welcome, this is useful information that we can put in our README as well. Have fun!
