### ISSUE TITLE
About -flag

### ISSUE THREAD

**Issue by Zeno-Code** [kataras/rizla#13]
```go
func main() {
	host := flag.String("host", "abc.com", "domain")
	flag.Parse()
	fmt.Printf("%#v", *host)
}
`

main -host abcde.com
"abcde.com"

rizla main.go -host abcde.com
"abc.com"

what should I do？

**Comment by kataras** [comment]
Flags are passed via the code method but not from the cli, I will fix it @Zeno-Code , thank you for the report!

**Comment by kataras** [comment]
Update with `go get -u github.com/kataras/rizla` and you should be able to run: `rizla main.go -host abcde.com` as you requested

**Comment by Zeno-Code** [comment]
It worked
Very helpful when developing
Thanks

**Comment by Zeno-Code** [comment]
A new problem @kataras 

Multi parameter

rizla main.go -a abc -b cde

missing a

**Comment by kataras** [comment]
Thanks @Zeno-Code , fixed :)
