### ISSUE TITLE
Can not find "github.com/iris-contrib/color"?

### ISSUE THREAD

**Issue by TIGERB** [kataras/rizla#16]
In the file "printer.go"

```
package rizla

import (
	"os"

	"github.com/iris-contrib/color"
	"github.com/mattn/go-colorable"
)

// Printer the printer for a rizla instance
type Printer struct {
	*color.Color
	// stream is the output stream which the program will use
	stream *os.File
}

// NewPrinter returns a new colorable printer
func NewPrinter(out *os.File) *Printer {
	c := color.New(colorable.NewColorable(out))
	return &Printer{
		Color:  c,
		stream: out,
	}
}
...
```

But is "github.com/fatih/color" in the file main.go.

Check it please!

**Comment by TIGERB** [comment]
I know this reason, because I get it by glide. The glide give me the version is 0.0.6. you should publish a new release.thx~

**Comment by ghost** [comment]
it's same problem for me ,how to solve it @TIGERB

**Comment by TIGERB** [comment]
I'm so sorry, I forget it.

**Comment by kataras** [comment]
Ah I see, sorry for the delay, rizla's latest version was tagged but not released. The issue is that glide fetches an older version. Fixed, thanks!

**Comment by kataras** [comment]
https://github.com/kataras/rizla/releases/tag/v0.1.1
