### ISSUE TITLE
Error 128 when editing go files

### ISSUE THREAD

**Issue by brunocassol** [kataras/rizla#7]
Rizla is giving me `A change has been detected, reloading now...exit status 128` when I edit a .go file.

I just finished setting up Go 1.8 on Windows 10. I don't use anti-virus software.

Created hello.go file:
```
package main

import "fmt"

func main() {
	fmt.Println("Hello world")
}
```

Running rizla works:
`rizla.exe src/hello/hello.go`
`Hello world`

But when I edit hello.go it gives me this:
![image](https://cloud.githubusercontent.com/assets/203541/23690209/33c578ac-0396-11e7-94ed-722386fbf084.png)

I tried running rizla with -walk, it wont detect changes.
I tried running rizla from a terminal with admin rights and got same error: "...exit status 128"

Any ideas how I could get rizla to work?

Thanks in advance!

**Comment by kataras** [comment]
@brunocassol It has nothing to do with Rizla(directly) I just tried it on a machine like yours and Rizla is working like a charm 🥇 so far.

I'm guessing that you using an editor which overrides the operating system's file system events(signals). 

Editors like Atom, LiteIDE, Sublime, Notepad++, Notepad, VS Code are working . 

IntelliJ Goglang didn't work but I had a contact a month ago telling that they made it to work as expected and now it's working with Rizla (this is not tested by myself).

Thanks,
kataras

**Comment by brunocassol** [comment]
Thanks for your reply. I'm using VS Code. For a HelloWorld rizla acts like schrodinger's cat :cat2: over here :

![rizla](https://cloud.githubusercontent.com/assets/203541/23756779/2bfb873a-04bb-11e7-9e30-9be13d24534d.gif)

Interestingly rizla seems to behave better with larger applications, specially ones that don't terminate right away like web servers. In this case it is much more reliable but still gives error 128 from time to time. Specially when there's a compilation error. Which leads me to think it might have some problems when the go application is short-lived.

**Comment by brunocassol** [comment]
I'll try to debug this and hopefully submit a PR once I'm a bit more experienced with Go.

For now I'm using rizla to develop a small web application using Echo/GORM and it is already very useful even when not working 100%.

So thank you a ton already!
